markdown: kramdown
highlighter: pygments
baseurl: /behaviac
permalink: /behaviac/news/:year/:month/:day/:title/
excerpt_separator: ""

gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-11132649-2

repository: https://github.com/TencentOpen/behaviac
help_url: https://github.com/TencentOpen/behaviac
collections:
  docs:
    output: true

name: Behaviac â€¢ Simple, Game AI, Offfical  Website
description: Advance Game AI framework, support Unity 3D, Cocos 2d, SDL and other game engine.
url: http://tencentopen.github.io/behaviac/

gems:
  - jekyll-feed
